version: '2'
services:
  python:
    image: python:dev
    volumes:
      - ./python/:/code
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python mypackage/run.py
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
      - POSTGRES_HOST=postgres

  python-tests:
    image: python:dev
    volumes:
      - ./python/:/code
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." pytest
    depends_on:
      - python

  python3.5:
    image: python3.5:dev
    volumes:
      - ./python/:/code
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python mypackage/run.py
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
      - POSTGRES_HOST=postgres

  python3.5-tests:
    image: python3.5:dev
    volumes:
      - ./python/:/code
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." pytest
    depends_on:
      - python3.5

  python3.6:
    image: python3.6:dev
    volumes:
      - ./python/:/code
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python mypackage/run.py
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
      - POSTGRES_HOST=postgres

  python3.6-tests:
    image: python3.6:dev
    volumes:
      - ./python/:/code
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." pytest
    depends_on:
      - python3.6

  python3.7:
    image: python3.7:dev
    volumes:
      - ./python/:/code
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python mypackage/run.py
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
      - POSTGRES_HOST=postgres

  python3.7-tests:
    image: python3.7:dev
    volumes:
      - ./python/:/code
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." pytest
    depends_on:
      - python3.7


  java8:
    image: java8:dev
    volumes:
      - ./java/:/usr/src/app
    entrypoint: sh -c 'find src/ | entr mvn clean compile exec:java --batch-mode --quiet'
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
      - POSTGRES_HOST=postgres

  java9:
    image: java9:dev
    volumes:
      - ./java/:/usr/src/app
    entrypoint: sh -c 'find src/ | entr mvn clean compile exec:java --batch-mode --quiet'
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
      - POSTGRES_HOST=postgres

  java10:
    image: java10:dev
    volumes:
      - ./java/:/usr/src/app
    entrypoint: sh -c 'find src/ | entr mvn clean compile exec:java --batch-mode --quiet'
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
      - POSTGRES_HOST=postgres

  java11:
    image: java11:dev
    volumes:
      - ./java/:/usr/src/app
    entrypoint: sh -c 'find src/ | entr mvn clean compile exec:java --batch-mode --quiet'
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
      - POSTGRES_HOST=postgres

#  java13:
#    image: java13:dev
#    volumes:
#      - ./java/:/usr/src/app
#    entrypoint: sh -c 'find src/ | entr mvn clean compile exec:java --batch-mode --quiet'
#    depends_on:
#      - postgres
#    links:
#      - postgres
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=myproject
#      - POSTGRES_HOST=postgres

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
    volumes:
      - /data/aedspy/postgres:/var/lib/postgresql/data

  pgadminer:
    image: clue/adminer
    ports: 
      - "99:80"
